from __future__ import annotations

import csv
import json
import re
from functools import lru_cache
from html import unescape
from pathlib import Path

from hsk_card_generator.models import WordEntry


ROOT = Path(__file__).resolve().parent.parent


HSK1_SAMPLE: list[WordEntry] = [
    WordEntry(1, "你", "nǐ", "you", "ты / вы"),
    WordEntry(2, "好", "hǎo", "hello", "привет"),
    WordEntry(3, "他", "tā", "he", "он"),
    WordEntry(4, "她", "tā", "she", "она"),
    WordEntry(5, "我", "wǒ", "I", "я"),
    WordEntry(6, "是", "shì", "am / is / are", "быть"),
    WordEntry(7, "吗", "ma", "question particle", "вопрос. частица"),
    WordEntry(8, "不", "bù", "no / not", "нет / не"),
    WordEntry(9, "了", "le", "aspect particle", "частица аспекта"),
    WordEntry(10, "在", "zài", "in / at", "в / на"),
    WordEntry(11, "有", "yǒu", "have", "иметь"),
    WordEntry(12, "和", "hé", "and", "и"),
    WordEntry(13, "人", "rén", "person", "человек"),
    WordEntry(14, "这", "zhè", "this / these", "этот / эти"),
    WordEntry(15, "中", "zhōng", "middle / center", "середина / центр"),
    WordEntry(16, "大", "dà", "big", "большой"),
    WordEntry(17, "来", "lái", "come", "приходить"),
    WordEntry(18, "上", "shàng", "on / up", "на / вверх"),
    WordEntry(19, "个", "gè", "measure word", "счётное слово"),
    WordEntry(20, "国", "guó", "country", "страна"),
    WordEntry(21, "我们", "wǒmen", "we", "мы"),
    WordEntry(22, "去", "qù", "go", "идти"),
    WordEntry(23, "说", "shuō", "say / speak", "говорить"),
    WordEntry(24, "为", "wèi", "for", "для / ради"),
    WordEntry(25, "子", "zǐ", "child / son", "ребёнок / сын"),
    WordEntry(26, "生", "shēng", "life / birth", "жизнь / рождение"),
    WordEntry(27, "会", "huì", "can / will", "мочь / уметь"),
    WordEntry(28, "到", "dào", "arrive / reach", "прибывать / достигать"),
    WordEntry(29, "时", "shí", "time / hour", "время / час"),
    WordEntry(30, "要", "yào", "want / need", "хотеть / нужно"),
    WordEntry(31, "出", "chū", "go out", "выходить"),
    WordEntry(32, "也", "yě", "also / too", "тоже / также"),
    WordEntry(33, "学", "xué", "study", "учиться"),
    WordEntry(34, "下", "xià", "down / below", "вниз / ниже"),
    WordEntry(35, "对", "duì", "right / correct", "правильно / верно"),
    WordEntry(36, "去", "qù", "go", "идти"),
    WordEntry(37, "能", "néng", "can / be able", "мочь / уметь"),
    WordEntry(38, "后", "hòu", "after / behind", "после / позади"),
    WordEntry(39, "就", "jiù", "then / just", "тогда / просто"),
    WordEntry(40, "多", "duō", "many / much", "много / многие"),
    WordEntry(41, "小", "xiǎo", "small", "маленький"),
    WordEntry(42, "心", "xīn", "heart / mind", "сердце / душа"),
    WordEntry(43, "而", "ér", "but / however", "но / однако"),
    WordEntry(44, "天", "tiān", "sky / day", "небо / день"),
    WordEntry(45, "没", "méi", "not have / without", "не иметь / без"),
    WordEntry(46, "从", "cóng", "from", "от / из"),
    WordEntry(47, "那", "nà", "that / there", "тот / та"),
    WordEntry(48, "得", "dé", "get / obtain", "получать / достать"),
    WordEntry(49, "地", "de", "particle", "частица места"),
    WordEntry(50, "把", "bǎ", "hold / grasp", "держать / брать"),
]


_HUNGARIAN = [
    "te / ön",
    "szia / jó",
    "ő (férfi)",
    "ő (nő)",
    "én",
    "lenni",
    "kérdő partikula",
    "nem",
    "befejezett aspektus",
    "-ban / -ben / -nál",
    "van / birtokol",
    "és",
    "ember",
    "ez / ezek",
    "közép",
    "nagy",
    "jön",
    "fent / rajta",
    "számlálószó",
    "ország",
    "mi",
    "menni",
    "mond / beszél",
    "számára / miatt",
    "gyermek / fiú",
    "élet / születés",
    "tud / fog",
    "megérkezik / elér",
    "idő / óra",
    "akar / kell",
    "kimegy",
    "is / szintén",
    "tanul",
    "le / lent",
    "helyes / jó",
    "menni",
    "képes / tud",
    "után / mögött",
    "akkor / éppen",
    "sok",
    "kicsi",
    "szív / elme",
    "de / azonban",
    "ég / nap",
    "nincs / nélkül",
    "-tól / -ből",
    "az / ott",
    "kap / megszerez",
    "partikula",
    "fog / tart",
]

for _word, _hungarian in zip(HSK1_SAMPLE, _HUNGARIAN):
    _word.hungarian = _hungarian


LOOKUP = {word.chinese: word for word in HSK1_SAMPLE}


DATASET_META = [
    {
        "id": "hsk1_old",
        "label": "HSK1 (old)",
        "group": "HSK",
        "standard": "HSK 2.0",
        "count": 150,
        "source": "plaktos/hsk_csv hsk1.csv",
    },
    {
        "id": "hsk2_old",
        "label": "HSK2 (old)",
        "group": "HSK",
        "standard": "HSK 2.0 cumulative",
        "count": 300,
        "source": "plaktos/hsk_csv hsk1.csv + hsk2.csv",
    },
    {
        "id": "hsk1_new",
        "label": "HSK1 (new / 3.0)",
        "group": "HSK",
        "standard": "HSK 3.0 / 2025",
        "count": 300,
        "source": "Chinese Language Hub hsk-1.json",
    },
    {
        "id": "hsk2_new",
        "label": "HSK2 (new / 3.0)",
        "group": "HSK",
        "standard": "HSK 3.0 / 2025 cumulative",
        "count": 497,
        "source": "Chinese Language Hub hsk-1.json + hsk-2.json",
    },
    {
        "id": "core_multilingual_300",
        "label": "Core multilingual 300",
        "group": "Other languages",
        "standard": "Starter EN/HU/RU/ZH core",
        "count": 300,
        "source": "Local starter set from prepared HSK 3.0 multilingual rows",
    },
    {
        "id": "core_english_hungarian_300",
        "label": "English-Hungarian core 300",
        "group": "Other languages",
        "standard": "Starter EN/HU focus",
        "count": 300,
        "source": "Local starter set from prepared multilingual core rows",
    },
    {
        "id": "top_english_300",
        "label": "Top English 300",
        "group": "Other languages",
        "standard": "English frequency forms",
        "count": 300,
        "source": "Top 300 Most Common English Words frequency list",
    },
    {
        "id": "top_hungarian_300",
        "label": "Top Hungarian 300",
        "group": "Other languages",
        "standard": "Hungarian frequency forms",
        "count": 300,
        "source": "Wiktionary Hungarian frequency list",
    },
]


def get_hsk1_sample() -> list[dict]:
    return [word.to_dict() for word in get_dataset_words("hsk1_old")[:50]]


def get_dataset_list() -> list[dict]:
    datasets = []
    for item in DATASET_META:
        words = get_dataset_words(item["id"])
        datasets.append({**item, "count": len(words)})
    return datasets


def get_dataset(dataset_id: str | None) -> dict:
    dataset_id = dataset_id or "hsk1_old"
    meta = next((item for item in DATASET_META if item["id"] == dataset_id), DATASET_META[0])
    words = get_dataset_words(meta["id"])
    return {**meta, "count": len(words), "words": [word.to_dict() for word in words]}


@lru_cache(maxsize=8)
def get_dataset_words(dataset_id: str) -> tuple[WordEntry, ...]:
    if dataset_id == "hsk1_old":
        return tuple(_load_old_dataset(["data_hsk_old_1.csv"]))
    if dataset_id == "hsk2_old":
        return tuple(_load_old_dataset(["data_hsk_old_1.csv", "data_hsk_old_2.csv"]))
    if dataset_id == "hsk1_new":
        return tuple(_load_new_dataset(["data_hsk1_new.json"]))
    if dataset_id == "hsk2_new":
        return tuple(_load_new_dataset(["data_hsk1_new.json", "data_hsk2_new.json"]))
    if dataset_id in ("core_multilingual_300", "core_english_hungarian_300"):
        return tuple(_renumber_words(list(_load_new_dataset(["data_hsk1_new.json"]))[:300]))
    if dataset_id == "top_english_300":
        return tuple(_build_top_english_dataset())
    if dataset_id == "top_hungarian_300":
        return tuple(_build_top_hungarian_dataset())
    return tuple(HSK1_SAMPLE)


def _build_top_english_dataset() -> list[WordEntry]:
    words: list[WordEntry] = []
    for i, word in enumerate(_split_words(TOP_ENGLISH_300)[:300], start=1):
        chinese = _english_to_chinese(word)
        words.append(WordEntry(
            index=i,
            chinese=chinese,
            pinyin=_pinyin_for_chinese(chinese),
            english=word,
            target=_translate_fallback(word, "ru"),
            hungarian=_translate_fallback(word, "hu"),
        ))
    return words


def _build_top_hungarian_dataset() -> list[WordEntry]:
    words: list[WordEntry] = []
    for i, word in enumerate(_split_words(TOP_HUNGARIAN_300)[:300], start=1):
        chinese = _hungarian_to_chinese(word)
        words.append(WordEntry(
            index=i,
            chinese=chinese,
            pinyin=_pinyin_for_chinese(chinese),
            english=_translate_hungarian(word, "en"),
            target=_translate_hungarian(word, "ru"),
            hungarian=word,
        ))
    return words


def _split_words(raw: str) -> list[str]:
    return [item.strip() for item in raw.split() if item.strip()]


def _english_to_chinese(word: str) -> str:
    normalized = word.lower()
    for entry in get_dataset_words("hsk2_new"):
        if entry.english.lower().split(";")[0].split(",")[0].strip() == normalized:
            return entry.chinese
    if normalized in COMMON_ENGLISH_CHINESE:
        return COMMON_ENGLISH_CHINESE[normalized]
    if any(separator in normalized for separator in (" / ", ";", ",")):
        for part in re.split(r"\s*/\s*|;|,", normalized):
            chinese = _english_to_chinese(part.strip())
            if chinese:
                return chinese
    return ""


def _pinyin_for_chinese(chinese: str) -> str:
    if not chinese:
        return ""
    for entry in get_dataset_words("hsk2_new"):
        if entry.chinese == chinese:
            return entry.pinyin
    return COMMON_CHINESE_PINYIN.get(chinese, "")


def _hungarian_to_chinese(word: str) -> str:
    english = _translate_hungarian(word, "en")
    return _english_to_chinese(english) if english != word else ""


def _renumber_words(words: list[WordEntry]) -> list[WordEntry]:
    return [
        WordEntry(
            index=i,
            chinese=word.chinese,
            pinyin=word.pinyin,
            english=word.english,
            target=word.target,
            hungarian=word.hungarian,
            lockedFields=list(word.lockedFields),
        )
        for i, word in enumerate(words, start=1)
    ]


def _load_old_dataset(file_names: list[str]) -> list[WordEntry]:
    rows: list[tuple[str, str, str]] = []
    for file_name in file_names:
        path = ROOT / file_name
        if not path.exists():
            continue
        with path.open(encoding="utf-8-sig", newline="") as file:
            rows.extend((row[0], row[1], row[2]) for row in csv.reader(file) if len(row) >= 3)
    return _rows_to_words(rows)


def _load_new_dataset(file_names: list[str]) -> list[WordEntry]:
    rows: list[tuple[str, str, str]] = []
    for file_name in file_names:
        path = ROOT / file_name
        if not path.exists():
            continue
        data = json.loads(path.read_text(encoding="utf-8"))
        rows.extend((item["simplified"], item["pinyin"], item["english"]) for item in data.get("terms", []))
    return _rows_to_words(rows)


def _rows_to_words(rows: list[tuple[str, str, str]]) -> list[WordEntry]:
    russian_by_hanzi = _russian_map_from_chineseplus()
    hungarian_by_hanzi = _hungarian_map_from_new_hsk()
    words: list[WordEntry] = []
    for hanzi, pinyin, english in rows:
        known = LOOKUP.get(hanzi)
        target = known.target if known and known.target else russian_by_hanzi.get(hanzi) or _translate_fallback(english, "ru")
        hungarian = known.hungarian if known and known.hungarian else hungarian_by_hanzi.get(hanzi) or _translate_fallback(english, "hu")
        words.append(
            WordEntry(
                index=len(words) + 1,
                chinese=hanzi,
                pinyin=pinyin,
                english=_clean_english(english),
                target=target,
                hungarian=hungarian,
            )
        )
    return words


@lru_cache(maxsize=1)
def _russian_map_from_chineseplus() -> dict[str, str]:
    pattern = re.compile(
        r"<tr[^>]*>.*?<td><!--t=[^>]+-->(?P<n>\d+).*?"
        r"<h2[^>]*><!--t=[^>]+-->(?P<hanzi>.*?)<!----></h2>.*?"
        r"<td[^>]*q:key=\"zP_1\"><!--t=[^>]+-->(?P<pinyin>.*?)<!----></td>.*?"
        r"<div[^>]*word-wrap:break-word;white-space:normal\"><!--t=[^>]+-->(?P<ru>.*?)<!----></div>",
        re.S,
    )
    result: dict[str, str] = {}
    for file_name in ("data_chineseplus_hsk2_ru.html", "data_chineseplus_hsk2_level2_ru.html"):
        path = ROOT / file_name
        if not path.exists():
            continue
        text = path.read_text(encoding="utf-8", errors="ignore")
        for match in pattern.finditer(text):
            hanzi = _strip_tags(match.group("hanzi"))
            ru = _strip_tags(match.group("ru"))
            if hanzi and ru:
                result[hanzi] = ru
    return result


@lru_cache(maxsize=1)
def _hungarian_map_from_new_hsk() -> dict[str, str]:
    result: dict[str, str] = {}
    for file_name in ("data_hsk1_new.json", "data_hsk2_new.json"):
        path = ROOT / file_name
        if not path.exists():
            continue
        data = json.loads(path.read_text(encoding="utf-8"))
        for item in data.get("terms", []):
            hanzi = item.get("simplified")
            english = item.get("english")
            if hanzi and english and hanzi not in result:
                result[hanzi] = _translate_fallback(english, "hu")
    return result


def _strip_tags(value: str) -> str:
    value = re.sub(r"<[^>]+>", "", value)
    value = unescape(value)
    return " ".join(value.split())


def _clean_english(value: str) -> str:
    value = re.sub(r"\s+", " ", value).strip()
    value = value.replace("to ", "", 1) if value.startswith("to ") else value
    return value


EXACT_TRANSLATIONS: dict[str, tuple[str, str]] = {
    "love": ("любовь / любить", "szerelem / szeret"),
    "eight": ("восемь", "nyolc"),
    "dad": ("папа", "apa"),
    "father": ("отец", "apa"),
    "hundred": ("сто", "száz"),
    "daytime": ("дневное время", "nappal"),
    "half": ("половина", "fél"),
    "cup": ("чашка / стакан", "csésze / pohár"),
    "side": ("сторона", "oldal"),
    "illness; sick": ("болезнь / больной", "betegség / beteg"),
    "not": ("не / нет", "nem"),
    "dish; vegetable": ("блюдо / овощ", "étel / zöldség"),
    "tea": ("чай", "tea"),
    "sing": ("петь", "énekel"),
    "supermarket": ("супермаркет", "szupermarket"),
    "car; vehicle": ("машина / транспорт", "autó / jármű"),
    "eat": ("есть / кушать", "eszik"),
    "wear": ("носить / надевать", "visel / felvesz"),
    "taxi": ("такси", "taxi"),
    "big; large": ("большой", "nagy"),
    "everyone": ("все", "mindenki"),
    "arrive; to": ("прибывать / до", "megérkezik / -hoz"),
    "university": ("университет", "egyetem"),
    "possessive particle": ("частица принадлежности", "birtokos partikula"),
    "store": ("магазин", "bolt / üzlet"),
    "telephone": ("телефон", "telefon"),
    "computer": ("компьютер", "számítógép"),
    "television": ("телевизор", "televízió"),
    "movie": ("фильм", "film"),
    "younger brother": ("младший брат", "öcs"),
    "things; stuff": ("вещи", "dolgok"),
    "all": ("все", "mind"),
    "read": ("читать", "olvas"),
    "correct; towards": ("правильный / к", "helyes / felé"),
    "sorry": ("извините", "bocsánat"),
    "many; much": ("много", "sok"),
    "two": ("два", "kettő"),
    "son": ("сын", "fiú"),
    "rice; meal": ("рис / еда", "rizs / étkezés"),
    "room": ("комната", "szoba"),
    "very; extremely": ("очень", "nagyon"),
    "airplane": ("самолёт", "repülőgép"),
    "minute": ("минута", "perc"),
    "happy": ("радостный", "boldog"),
    "measure word": ("счётное слово", "számlálószó"),
    "song": ("песня", "dal"),
    "older brother": ("старший брат", "báty"),
    "give; for": ("давать / для", "ad / számára"),
    "company": ("компания", "cég"),
    "work; job": ("работа", "munka"),
    "expensive": ("дорогой", "drága"),
    "country": ("страна", "ország"),
    "still; yet": ("ещё / всё ещё", "még"),
    "child; children": ("ребёнок / дети", "gyerek / gyerekek"),
    "Chinese (language)": ("китайский язык", "kínai nyelv"),
    "Chinese character": ("китайский иероглиф", "kínai írásjegy"),
    "number; date": ("номер / дата", "szám / dátum"),
    "good": ("хороший", "jó"),
    "delicious": ("вкусный", "finom"),
    "beautiful": ("красивый", "szép"),
    "and; with": ("и / с", "és / -val"),
    "to drink": ("пить", "iszik"),
    "very": ("очень", "nagyon"),
    "behind; after": ("сзади / после", "mögött / után"),
    "return; go back": ("возвращаться", "visszatér"),
    "can; will; meeting": ("мочь / собрание", "tud / fog / találkozó"),
    "train": ("поезд", "vonat"),
    "how many; several": ("сколько / несколько", "hány / néhány"),
    "home; family": ("дом / семья", "otthon / család"),
    "to see; to meet": ("видеть / встречать", "lát / találkozik"),
    "call; be named": ("звать / называться", "hív / nevezik"),
    "dumpling": ("пельмень / цзяоцзы", "gombóc / jiaozi"),
    "egg": ("яйцо", "tojás"),
    "older sister": ("старшая сестра", "nővér"),
    "this year": ("этот год", "ez az év"),
    "today": ("сегодня", "ma"),
    "nine": ("девять", "kilenc"),
    "to feel; to think": ("чувствовать / думать", "érez / gondol"),
    "to open; to turn on": ("открывать / включать", "kinyit / bekapcsol"),
    "to see; to look; to watch": ("смотреть / видеть", "néz / lát"),
    "class; lesson": ("урок / занятие", "óra / lecke"),
    "mouth": ("рот", "száj"),
    "to come": ("приходить", "jön"),
    "teacher": ("учитель", "tanár"),
    "cold": ("холодный", "hideg"),
    "inside": ("внутри", "belül"),
    "zero": ("ноль", "nulla"),
    "six": ("шесть", "hat"),
    "question particle": ("вопросительная частица", "kérdő partikula"),
    "sell": ("продавать", "elad"),
    "to buy": ("покупать", "vesz"),
    "busy": ("занятый", "elfoglalt"),
    "mom": ("мама", "anya"),
    "younger sister": ("младшая сестра", "húg"),
    "bread": ("хлеб", "kenyér"),
    "name": ("имя", "név"),
    "that": ("тот / та", "az"),
    "which; where": ("который / где", "melyik / hol"),
    "male": ("мужской", "férfi"),
    "female": ("женский", "női"),
    "friend": ("друг", "barát"),
    "cheap": ("дешёвый", "olcsó"),
    "apple": ("яблоко", "alma"),
    "seven": ("семь", "hét"),
    "front; before": ("перед / до", "elöl / előtt"),
    "money": ("деньги", "pénz"),
    "thousand": ("тысяча", "ezer"),
    "please; invite": ("пожалуйста / приглашать", "kérem / meghív"),
    "to go": ("идти / ехать", "megy"),
    "hot": ("горячий", "forró"),
    "person; people": ("человек / люди", "ember / emberek"),
    "day; date": ("день / дата", "nap / dátum"),
    "three": ("три", "három"),
    "up; go up": ("верх / подниматься", "fel / felmegy"),
    "morning": ("утро", "reggel"),
    "who": ("кто", "ki"),
    "what": ("что", "mi"),
    "ten": ("десять", "tíz"),
    "matter; thing; affair": ("дело / вещь", "ügy / dolog"),
    "is; are; am": ("быть / есть", "lenni"),
    "time": ("время", "idő"),
    "mobile phone": ("мобильный телефон", "mobiltelefon"),
    "book": ("книга", "könyv"),
    "to sleep": ("спать", "alszik"),
    "water": ("вода", "víz"),
    "fruit": ("фрукт", "gyümölcs"),
    "to say; to speak": ("говорить", "mond / beszél"),
    "four": ("четыре", "négy"),
    "he; him": ("он / его", "ő"),
    "she; her": ("она / её", "ő"),
    "too; extremely": ("слишком / очень", "túl / nagyon"),
    "day; sky": ("день / небо", "nap / ég"),
    "weather": ("погода", "időjárás"),
    "listen": ("слушать", "hallgat"),
    "outside; external": ("снаружи / внешний", "kívül / külső"),
    "play, have fun": ("играть / развлекаться", "játszik / szórakozik"),
    "late; evening": ("поздний / вечер", "késő / este"),
    "ask": ("спрашивать", "kérdez"),
    "question": ("вопрос", "kérdés"),
    "I; me": ("я / меня", "én / engem"),
    "we; us": ("мы / нас", "mi / minket"),
    "five": ("пять", "öt"),
    "down; under": ("вниз / под", "le / alatt"),
    "want; think": ("хотеть / думать", "akar / gondol"),
    "Mr.; sir": ("господин", "úr"),
    "now": ("сейчас", "most"),
    "small": ("маленький", "kicsi"),
    "afternoon": ("день / после полудня", "délután"),
    "to write": ("писать", "ír"),
    "some": ("некоторые / немного", "néhány"),
    "thank you": ("спасибо", "köszönöm"),
    "new": ("новый", "új"),
    "week; day of the week": ("неделя / день недели", "hét / hét napja"),
    "Sunday": ("воскресенье", "vasárnap"),
    "rest": ("отдыхать", "pihen"),
    "learn; study": ("учиться", "tanul"),
    "snow": ("снег", "hó"),
    "student": ("студент / ученик", "diák"),
    "school": ("школа", "iskola"),
    "to want; to need": ("хотеть / нужно", "akar / kell"),
    "also; too": ("тоже / также", "is / szintén"),
    "one": ("один", "egy"),
    "doctor": ("врач", "orvos"),
    "hospital": ("больница", "kórház"),
    "chair": ("стул", "szék"),
    "have; there is/are": ("иметь / есть", "van / birtokol"),
    "rain": ("дождь", "eső"),
    "yuan (currency)": ("юань", "jüan"),
    "month; moon": ("месяц / луна", "hónap / hold"),
    "again; once more": ("снова", "újra"),
    "at; in; on": ("в / на / у", "-ban / -ben / -on"),
    "goodbye": ("до свидания", "viszlát"),
    "early; morning": ("ранний / утро", "korán / reggel"),
    "how; why": ("как / почему", "hogyan / miért"),
    "how about": ("как насчёт", "mi lenne"),
    "to look for": ("искать", "keres"),
    "this": ("этот / эта", "ez"),
    "here": ("здесь", "itt"),
    "really; truly": ("действительно", "tényleg / igazán"),
    "only": ("только", "csak"),
    "know": ("знать", "tud / ismer"),
    "China": ("Китай", "Kína"),
    "noon": ("полдень", "dél"),
    "live; reside": ("жить", "lakik / él"),
    "table": ("стол", "asztal"),
    "character; word": ("иероглиф / слово", "írásjegy / szó"),
    "sit; take (transport)": ("сидеть / ехать", "ül / utazik"),
    "do; make": ("делать", "csinál"),
    "yesterday": ("вчера", "tegnap"),
    "don't": ("не надо / не", "ne / ne tedd"),
    "make a phone call": ("звонить по телефону", "telefonál"),
    "o'clock; point": ("час / точка", "óra / pont"),
    "cinema": ("кинотеатр", "mozi"),
    "dog": ("собака", "kutya"),
    "pleasant to hear": ("приятный на слух", "kellemes hallani"),
    "fun; interesting": ("весёлый / интересный", "szórakoztató / érdekes"),
    "item": ("предмет", "darab / tétel"),
    "drive": ("водить машину", "vezet"),
    "cat": ("кот / кошка", "macska"),
    "it doesn't matter": ("ничего / неважно", "nem számít"),
    "don't have; there isn't": ("нет / не иметь", "nincs / nincs neki"),
    "plural marker": ("показатель мн. числа", "többesjel"),
    "noodles": ("лапша", "tészta"),
    "cooked rice": ("варёный рис", "főtt rizs"),
    "tomorrow": ("завтра", "holnap"),
    "over there": ("там", "ott / amott"),
    "that one": ("тот", "az az egy"),
    "which one": ("который", "melyik"),
    "there": ("там", "ott"),
    "where": ("где", "hol"),
    "those": ("те", "azok"),
    "which (plural)": ("которые", "melyek"),
    "hello": ("привет", "szia"),
    "you (plural)": ("вы / вы все", "ti / önök"),
    "you (polite form)": ("вы (вежл.)", "ön"),
    "milk": ("молоко", "tej"),
    "daughter": ("дочь", "lánygyermek"),
    "lady; Ms.": ("госпожа", "hölgy"),
    "get out of bed": ("вставать с кровати", "felkel"),
    "excuse me; may I ask": ("извините / можно спросить", "elnézést / kérdezhetek"),
    "attend class": ("быть на уроке", "órán van"),
    "fall ill": ("заболеть", "megbetegszik"),
    "it": ("оно / это", "az"),
    "they; them (male or mixed group)": ("они", "ők"),
    "they": ("они", "ők"),
    "they; them (female group)": ("они (жен.)", "ők"),
    "hear": ("слышать", "hall"),
    "classmate": ("одноклассник", "osztálytárs"),
    "outside": ("снаружи", "kint / kívül"),
    "dinner": ("ужин", "vacsora"),
    "evening; night": ("вечер / ночь", "este / éjszaka"),
    "feed": ("кормить", "etet"),
    "lunch": ("обед", "ebéd"),
    "finish class": ("закончить урок", "befejezi az órát"),
    "hour": ("час", "óra"),
    "like": ("нравиться", "kedvel / szeret"),
    "a little; some": ("немного", "egy kicsit / néhány"),
    "clothes": ("одежда", "ruha"),
    "a moment, briefly": ("ненадолго / момент", "egy pillanat / röviden"),
    "a little bit": ("немного", "egy kicsit"),
    "breakfast": ("завтрак", "reggeli"),
    "this side; here": ("эта сторона / здесь", "ez az oldal / itt"),
    "this one": ("этот", "ez az egy"),
    "in the process of; currently": ("в процессе / сейчас", "éppen / jelenleg"),
    "these": ("эти", "ezek"),
    "cook": ("готовить", "főz"),
    "ah": ("ах", "á / ah"),
    "hobby": ("хобби", "hobbi"),
    "white": ("белый", "fehér"),
    "class": ("класс / урок", "osztály / óra"),
    "help": ("помогать", "segít"),
    "bag": ("сумка", "táska"),
    "compare; than": ("сравнивать / чем", "összehasonlít / mint"),
    "pen": ("ручка", "toll"),
    "excuse me": ("извините", "elnézést"),
    "long": ("длинный", "hosszú"),
    "station": ("станция", "állomás"),
    "bed": ("кровать", "ágy"),
    "word": ("слово", "szó"),
    "since childhood": ("с детства", "gyerekkor óta"),
    "wrong": ("неправильный", "rossz / hibás"),
    "hit; call; play": ("бить / звонить / играть", "üt / hív / játszik"),
    "take a taxi": ("ехать на такси", "taxival megy"),
    "open": ("открывать", "kinyit"),
    "but": ("но", "de"),
    "wait": ("ждать", "vár"),
    "subway": ("метро", "metró"),
    "move": ("двигать / переезжать", "mozog / költözik"),
    "understand": ("понимать", "ért"),
    "fly": ("летать", "repül"),
    "tall; high": ("высокий", "magas"),
    "tell; inform": ("сообщать", "elmond / tájékoztat"),
    "with; follow": ("с / следовать", "-val / követ"),
    "height": ("рост / высота", "magasság"),
    "bus": ("автобус", "busz"),
    "past": ("прошлый / мимо", "múlt / mellett"),
    "or; still": ("или / всё ещё", "vagy / még"),
    "black": ("чёрный", "fekete"),
    "red color": ("красный цвет", "piros szín"),
    "paint": ("рисовать / красить", "fest / rajzol"),
    "flower": ("цветок", "virág"),
    "classroom": ("классная комната", "tanterem"),
    "airport": ("аэропорт", "repülőtér"),
    "remember": ("помнить", "emlékszik"),
    "introduce": ("представлять", "bemutat"),
    "enter": ("входить", "belép"),
    "close, near": ("близко", "közel"),
    "frequently, often": ("часто", "gyakran"),
    "plane ticket": ("билет на самолёт", "repülőjegy"),
    "start": ("начинать", "kezd"),
    "take a test; examine": ("сдавать экзамен / проверять", "vizsgázik / megvizsgál"),
    "exam": ("экзамен", "vizsga"),
    "possibly": ("возможно", "lehetséges"),
    "fast; quick": ("быстрый", "gyors"),
    "about to": ("собираться", "mindjárt / készül"),
    "pants": ("брюки", "nadrág"),
    "basketball": ("баскетбол", "kosárlabda"),
    "tired": ("усталый", "fáradt"),
    "distance/from": ("расстояние / от", "távolság / -tól"),
    "building; floor": ("здание / этаж", "épület / emelet"),
    "road": ("дорога", "út"),
    "green color": ("зелёный цвет", "zöld szín"),
    "on the road": ("по дороге", "úton"),
    "travel": ("путешествовать", "utazik"),
    "slow": ("медленный", "lassú"),
    "every": ("каждый", "minden"),
    "boring, uninteresting": ("скучный", "unalmas"),
    "door": ("дверь", "ajtó"),
    "entrance; doorway": ("вход", "bejárat"),
    "ticket (for entry)": ("билет", "belépőjegy"),
    "take; to hold": ("брать / держать", "vesz / tart"),
    "grandmother (paternal)": ("бабушка по отцу", "apai nagymama"),
    "then": ("тогда / затем", "akkor / aztán"),
    "boy": ("мальчик", "fiú"),
    "that way": ("так / таким образом", "úgy / arrafelé"),
    "bird": ("птица", "madár"),
    "girl": ("девочка", "lány"),
    "beside; next to": ("рядом", "mellett"),
    "run": ("бегать", "fut"),
    "ticket": ("билет", "jegy"),
    "in front": ("спереди", "elöl"),
    "stand up; to rise": ("вставать / подниматься", "feláll / emelkedik"),
    "sunny": ("солнечный", "napos"),
    "ball; sports": ("мяч / спорт", "labda / sport"),
    "wife": ("жена", "feleség"),
    "let": ("позволять", "enged"),
    "above": ("сверху / выше", "fent / felett"),
    "surf the internet": ("сидеть в интернете", "internetezik"),
    "body; health": ("тело / здоровье", "test / egészség"),
    "thing": ("вещь", "dolog"),
    "hand": ("рука", "kéz"),
    "watch": ("смотреть / часы", "néz / óra"),
    "comfortable": ("удобный", "kényelmes"),
    "give as a gift; escort; deliver": ("дарить / сопровождать / доставлять", "ajándékoz / kísér / kézbesít"),
    "although; even though": ("хотя", "bár / habár"),
    "so; therefore": ("поэтому", "ezért"),
    "pain": ("боль", "fájdalom"),
    "kick": ("пинать", "rúg"),
    "strip": ("полоса", "csík"),
    "dance": ("танцевать", "táncol"),
    "head": ("голова", "fej"),
    "foreign country": ("заграница", "külföld"),
    "finish": ("заканчивать", "befejez"),
    "ten thousand": ("десять тысяч", "tízezer"),
    "forget": ("забывать", "elfelejt"),
    "towards": ("по направлению к", "felé"),
    "online; on the internet": ("онлайн / в интернете", "online / interneten"),
    "position / place (respectful)": ("место (вежл.)", "hely (udvarias)"),
    "why": ("почему", "miért"),
    "wash": ("мыть", "mos"),
    "below": ("ниже / снизу", "lent / alatt"),
    "smile; to laugh": ("улыбаться / смеяться", "mosolyog / nevet"),
    "childhood": ("детство", "gyerekkor"),
    "continue": ("продолжать", "folytat"),
    "surname": ("фамилия", "vezetéknév"),
    "restroom": ("туалет", "mosdó"),
    "hope": ("надеяться", "remél"),
    "eye": ("глаз", "szem"),
    "color": ("цвет", "szín"),
    "medicine": ("лекарство", "gyógyszer"),
    "pharmacy": ("аптека", "gyógyszertár"),
    "grandfather (paternal)": ("дедушка по отцу", "apai nagyapa"),
    "a moment; a while": ("момент / некоторое время", "pillanat / egy ideig"),
    "overcast": ("пасмурный", "borús"),
    "because": ("потому что", "mert"),
    "together": ("вместе", "együtt"),
    "meaning": ("значение", "jelentés"),
    "swim": ("плавать", "úszik"),
    "right (direction)": ("право / направо", "jobb / jobbra"),
    "interesting": ("интересный", "érdekes"),
    "right side": ("правая сторона", "jobb oldal"),
    "fish": ("рыба", "hal"),
    "far": ("далеко", "messze"),
    "exercise/sport": ("упражнение / спорт", "edzés / sport"),
    "stand; station": ("стоять / станция", "áll / állomás"),
    "husband": ("муж", "férj"),
    "indicating continuous action": ("показатель длительного действия", "folyamatos cselekvést jelöl"),
    "so, such": ("такой", "ilyen / olyan"),
    "just; currently": ("как раз / сейчас", "éppen / jelenleg"),
    "this way": ("так / сюда", "így / erre"),
    "week": ("неделя", "hét"),
    "prepare": ("готовить / подготавливать", "készül / előkészít"),
    "oneself": ("сам", "önmaga"),
    "walk": ("ходить пешком", "sétál / gyalogol"),
    "most; the best": ("самый / лучший", "leginkább / legjobb"),
    "left": ("левый", "bal"),
    "left side": ("левая сторона", "bal oldal"),
    "football; soccer": ("футбол", "foci / labdarúgás"),
    "beijing": ("Пекин", "Peking"),
    "train station": ("железнодорожная станция", "vasútállomás"),
    "young lady": ("девушка / мисс", "kisasszony / fiatal hölgy"),
    "assistance": ("помощь", "segítség"),
    "newspaper": ("газета", "újság"),
    "sing a song": ("петь песню", "énekel"),
    "lady; ms": ("госпожа", "hölgy"),
    "behind": ("сзади", "mögött"),
    "child": ("ребёнок", "gyerek"),
    "a boat": ("лодка", "hajó"),
    "play basketball": ("играть в баскетбол", "kosárlabdázik"),
    "first": ("первый", "első"),
    "waiter": ("официант", "pincér"),
    "kilogram (kg)": ("килограмм", "kilogramm"),
    "red": ("красный", "piros"),
    "reply": ("ответ", "válaszol / válasz"),
    "a man": ("мужчина", "férfi"),
    "woman": ("женщина", "nő"),
    "mutton": ("баранина", "birkehús"),
    "open up": ("открывать", "kinyit"),
    "bicycle": ("велосипед", "kerékpár"),
}

COMMON_ENGLISH_CHINESE: dict[str, str] = {
    "the": "这",
    "of": "的",
    "to": "到",
    "and": "和",
    "a": "一",
    "in": "在",
    "is": "是",
    "it": "它",
    "you": "你",
    "that": "那",
    "he": "他",
    "was": "是",
    "for": "为",
    "on": "上",
    "are": "是",
    "with": "和",
    "as": "像",
    "I": "我",
    "i": "我",
    "they": "他们",
    "be": "是",
    "at": "在",
    "one": "一",
    "have": "有",
    "this": "这",
    "from": "从",
    "or": "或",
    "by": "由",
    "but": "但是",
    "some": "一些",
    "what": "什么",
    "there": "那儿",
    "we": "我们",
    "can": "能",
    "out": "出",
    "other": "别的",
    "all": "都",
    "when": "什么时候",
    "up": "上",
    "use": "用",
    "word": "词",
    "how": "怎么",
    "an": "一",
    "she": "她",
    "which": "哪个",
    "do": "做",
    "time": "时",
    "if": "如果",
    "will": "会",
    "way": "路",
    "about": "关于",
    "many": "多",
    "then": "就",
    "write": "写",
    "like": "喜欢",
    "so": "所以",
    "these": "这些",
    "long": "长",
    "make": "做",
    "thing": "东西",
    "see": "看",
    "two": "二",
    "look": "看",
    "more": "更多",
    "day": "天",
    "go": "去",
    "come": "来",
    "sound": "声音",
    "no": "不",
    "number": "号",
    "who": "谁",
    "know": "知道",
    "water": "水",
    "call": "叫",
    "first": "第一",
    "people": "人",
    "down": "下",
    "side": "边",
    "now": "现在",
    "find": "找",
    "new": "新",
    "work": "工作",
    "part": "部分",
    "take": "拿",
    "get": "得到",
    "place": "地方",
    "live": "住",
    "where": "哪里",
    "after": "后",
    "back": "后",
    "little": "小",
    "only": "只",
    "man": "男人",
    "year": "年",
    "good": "好",
    "me": "我",
    "give": "给",
    "under": "下",
    "name": "名字",
    "very": "很",
    "through": "通过",
    "just": "就",
    "much": "多",
    "great": "大",
    "think": "想",
    "say": "说",
    "help": "帮助",
    "line": "线",
    "before": "前",
    "turn": "转",
    "move": "动",
    "right": "右",
    "boy": "男孩",
    "old": "老",
    "tell": "告诉",
    "sentence": "句子",
    "set": "放",
    "three": "三",
    "want": "要",
    "air": "空气",
    "well": "好",
    "also": "也",
    "play": "玩",
    "small": "小",
    "end": "结束",
    "put": "放",
    "home": "家",
    "read": "读",
    "hand": "手",
    "large": "大",
    "spell": "拼写",
    "add": "加",
    "even": "甚至",
    "land": "地",
    "here": "这里",
    "big": "大",
    "high": "高",
    "such": "这样",
    "follow": "跟",
    "act": "做",
    "why": "为什么",
    "ask": "问",
    "men": "男人",
    "change": "改变",
    "light": "光",
    "kind": "种",
    "off": "离开",
    "need": "需要",
    "house": "房子",
    "picture": "图片",
    "try": "试",
    "again": "再",
    "animal": "动物",
    "point": "点",
    "mother": "妈妈",
    "world": "世界",
    "near": "近",
    "build": "建",
    "earth": "地球",
    "father": "爸爸",
    "head": "头",
    "stand": "站",
    "country": "国",
    "answer": "回答",
    "school": "学校",
    "study": "学",
    "learn": "学",
    "plant": "植物",
    "food": "食物",
    "sun": "太阳",
    "four": "四",
    "eye": "眼睛",
    "door": "门",
    "city": "城市",
    "tree": "树",
    "hard": "难",
    "start": "开始",
    "story": "故事",
    "far": "远",
    "sea": "海",
    "draw": "画",
    "left": "左",
    "late": "晚",
    "run": "跑",
    "night": "晚上",
    "real": "真",
    "life": "生活",
    "few": "少",
    "stop": "停",
    "open": "开",
    "together": "一起",
    "next": "下一个",
    "white": "白",
    "children": "孩子",
    "walk": "走",
    "example": "例子",
    "paper": "纸",
    "music": "音乐",
    "book": "书",
    "letter": "字母",
    "river": "河",
    "car": "车",
    "feet": "脚",
    "care": "关心",
    "second": "第二",
    "group": "组",
    "rain": "雨",
    "eat": "吃",
    "room": "房间",
    "friend": "朋友",
    "idea": "想法",
    "fish": "鱼",
    "mountain": "山",
    "north": "北",
    "horse": "马",
    "cut": "切",
    "sure": "确定",
    "watch": "看",
    "color": "颜色",
    "face": "脸",
    "wood": "木头",
    "main": "主要",
}

COMMON_CHINESE_PINYIN: dict[str, str] = {
    "这": "zhè",
    "的": "de",
    "到": "dào",
    "和": "hé",
    "一": "yī",
    "在": "zài",
    "是": "shì",
    "它": "tā",
    "你": "nǐ",
    "那": "nà",
    "他": "tā",
    "为": "wèi",
    "上": "shàng",
    "像": "xiàng",
    "我": "wǒ",
    "他们": "tāmen",
    "有": "yǒu",
    "从": "cóng",
    "或": "huò",
    "由": "yóu",
    "但是": "dànshì",
    "一些": "yīxiē",
    "什么": "shénme",
    "那儿": "nàr",
    "我们": "wǒmen",
    "能": "néng",
    "出": "chū",
    "别的": "biéde",
    "都": "dōu",
    "什么时候": "shénme shíhou",
    "用": "yòng",
    "词": "cí",
    "怎么": "zěnme",
    "她": "tā",
    "哪个": "nǎge",
    "做": "zuò",
    "时": "shí",
    "如果": "rúguǒ",
    "会": "huì",
    "路": "lù",
    "关于": "guānyú",
    "多": "duō",
    "就": "jiù",
    "写": "xiě",
    "喜欢": "xǐhuān",
    "所以": "suǒyǐ",
    "这些": "zhèxiē",
    "长": "cháng",
    "东西": "dōngxi",
    "看": "kàn",
    "二": "èr",
    "更多": "gèng duō",
    "天": "tiān",
    "去": "qù",
    "来": "lái",
    "声音": "shēngyīn",
    "不": "bù",
    "号": "hào",
    "谁": "shéi",
    "知道": "zhīdào",
    "水": "shuǐ",
    "叫": "jiào",
    "第一": "dì yī",
    "人": "rén",
    "下": "xià",
    "边": "biān",
    "现在": "xiànzài",
    "找": "zhǎo",
    "新": "xīn",
    "工作": "gōngzuò",
    "部分": "bùfen",
    "拿": "ná",
    "得到": "dédào",
    "地方": "dìfang",
    "住": "zhù",
    "哪里": "nǎlǐ",
    "后": "hòu",
    "小": "xiǎo",
    "只": "zhǐ",
    "男人": "nánrén",
    "年": "nián",
    "好": "hǎo",
    "给": "gěi",
    "名字": "míngzi",
    "很": "hěn",
    "通过": "tōngguò",
    "大": "dà",
    "想": "xiǎng",
    "说": "shuō",
    "帮助": "bāngzhù",
    "线": "xiàn",
    "前": "qián",
    "转": "zhuǎn",
    "动": "dòng",
    "右": "yòu",
    "男孩": "nánhái",
    "老": "lǎo",
    "告诉": "gàosu",
    "句子": "jùzi",
    "放": "fàng",
    "三": "sān",
    "要": "yào",
    "空气": "kōngqì",
    "也": "yě",
    "玩": "wán",
    "结束": "jiéshù",
    "家": "jiā",
    "读": "dú",
    "手": "shǒu",
    "拼写": "pīnxiě",
    "加": "jiā",
    "甚至": "shènzhì",
    "地": "dì",
    "这里": "zhèlǐ",
    "高": "gāo",
    "这样": "zhèyàng",
    "跟": "gēn",
    "为什么": "wèishénme",
    "问": "wèn",
    "改变": "gǎibiàn",
    "光": "guāng",
    "种": "zhǒng",
    "离开": "líkāi",
    "需要": "xūyào",
    "房子": "fángzi",
    "图片": "túpiàn",
    "试": "shì",
    "再": "zài",
    "动物": "dòngwù",
    "点": "diǎn",
    "妈妈": "māma",
    "世界": "shìjiè",
    "近": "jìn",
    "建": "jiàn",
    "自己": "zìjǐ",
    "地球": "dìqiú",
    "爸爸": "bàba",
    "头": "tóu",
    "站": "zhàn",
    "页": "yè",
    "国": "guó",
    "回答": "huídá",
    "学校": "xuéxiào",
    "学": "xué",
    "植物": "zhíwù",
    "食物": "shíwù",
    "太阳": "tàiyáng",
    "四": "sì",
    "眼睛": "yǎnjing",
    "门": "mén",
    "城市": "chéngshì",
    "树": "shù",
    "难": "nán",
    "开始": "kāishǐ",
    "故事": "gùshi",
    "远": "yuǎn",
    "海": "hǎi",
    "画": "huà",
    "左": "zuǒ",
    "晚": "wǎn",
    "跑": "pǎo",
    "晚上": "wǎnshang",
    "真": "zhēn",
    "生活": "shēnghuó",
    "少": "shǎo",
    "停": "tíng",
    "开": "kāi",
    "一起": "yīqǐ",
    "下一个": "xià yī ge",
    "白": "bái",
    "孩子": "háizi",
    "走": "zǒu",
    "例子": "lìzi",
    "纸": "zhǐ",
    "音乐": "yīnyuè",
    "书": "shū",
    "字母": "zìmǔ",
    "河": "hé",
    "车": "chē",
    "脚": "jiǎo",
    "关心": "guānxīn",
    "第二": "dì èr",
    "组": "zǔ",
    "雨": "yǔ",
    "吃": "chī",
    "房间": "fángjiān",
    "朋友": "péngyou",
    "想法": "xiǎngfǎ",
    "鱼": "yú",
    "山": "shān",
    "北": "běi",
    "马": "mǎ",
    "切": "qiē",
    "确定": "quèdìng",
    "颜色": "yánsè",
    "脸": "liǎn",
    "木头": "mùtou",
    "主要": "zhǔyào",
}

COMMON_HUNGARIAN_TRANSLATIONS: dict[str, tuple[str, str]] = {
    "a": ("the", "артикль"),
    "az": ("that / the", "тот / артикль"),
    "hogy": ("that", "что / чтобы"),
    "nem": ("no / not", "нет / не"),
    "egy": ("one / a", "один / артикль"),
    "meg": ("and / also", "и / также"),
    "csak": ("only", "только"),
    "vagy": ("or", "или"),
    "van": ("is / there is", "есть / является"),
    "volt": ("was", "был"),
    "már": ("already", "уже"),
    "kell": ("need / must", "нужно / должен"),
    "még": ("still / yet", "ещё"),
    "és": ("and", "и"),
    "mint": ("as / than", "как / чем"),
    "azt": ("that", "то / это"),
    "akkor": ("then", "тогда"),
    "sem": ("neither / not either", "тоже не"),
    "lehet": ("can / may", "можно / может"),
    "mert": ("because", "потому что"),
    "minden": ("all / everything", "всё / каждый"),
    "olyan": ("such", "такой"),
    "szerint": ("according to", "согласно"),
    "pedig": ("however / whereas", "однако / же"),
    "ezt": ("this", "это"),
    "így": ("so / like this", "так"),
    "után": ("after", "после"),
    "úgy": ("so / that way", "так"),
    "nagy": ("big", "большой"),
    "fel": ("up", "вверх"),
    "majd": ("then / later", "потом"),
    "két": ("two", "два"),
    "nagyon": ("very", "очень"),
    "aki": ("who", "кто / который"),
    "most": ("now", "сейчас"),
    "több": ("more", "больше"),
    "lesz": ("will be", "будет"),
    "itt": ("here", "здесь"),
    "magyar": ("Hungarian", "венгерский"),
    "ami": ("what / which", "что / который"),
    "első": ("first", "первый"),
    "között": ("between", "между"),
    "hanem": ("but rather", "а / но"),
    "nincs": ("there is no", "нет"),
    "más": ("other", "другой"),
    "alatt": ("under", "под"),
    "sok": ("many / much", "много"),
    "ember": ("person", "человек"),
    "ott": ("there", "там"),
    "vagyok": ("I am", "я есть"),
    "mindig": ("always", "всегда"),
    "miatt": ("because of", "из-за"),
    "mellett": ("beside", "рядом"),
    "kis": ("small", "маленький"),
    "lenne": ("would be", "был бы"),
    "mit": ("what", "что"),
    "vannak": ("are / there are", "есть / находятся"),
    "előtt": ("before / in front", "перед"),
    "egész": ("whole", "целый"),
    "nélkül": ("without", "без"),
    "lett": ("became", "стал"),
    "ezért": ("therefore", "поэтому"),
    "igen": ("yes", "да"),
    "néhány": ("some", "несколько"),
    "ma": ("today", "сегодня"),
    "milyen": ("what kind", "какой"),
    "mind": ("all", "все"),
    "valami": ("something", "что-то"),
    "áll": ("stand", "стоять"),
    "tehát": ("therefore", "следовательно"),
    "három": ("three", "три"),
    "szó": ("word", "слово"),
    "fontos": ("important", "важный"),
    "jobb": ("better / right", "лучше / правый"),
    "nap": ("day", "день"),
    "dolog": ("thing", "вещь"),
    "szép": ("beautiful", "красивый"),
    "idő": ("time", "время"),
    "ország": ("country", "страна"),
    "négy": ("four", "четыре"),
    "megy": ("goes", "идёт"),
    "magas": ("tall / high", "высокий"),
}

COMMON_ENGLISH_TRANSLATIONS: dict[str, tuple[str, str]] = {
    "the": ("артикль", "a / az"),
    "of": ("из / принадлежность", "-nak / -nek"),
    "to": ("к / до", "-hoz / -hez / -höz"),
    "and": ("и", "és"),
    "a": ("один / артикль", "egy"),
    "in": ("в", "-ban / -ben"),
    "is": ("есть / является", "van"),
    "it": ("это / оно", "az"),
    "you": ("ты / вы", "te / ti"),
    "that": ("тот / что", "az / hogy"),
    "he": ("он", "ő"),
    "was": ("был", "volt"),
    "for": ("для / за", "számára / -ért"),
    "on": ("на", "-on / -en / -ön"),
    "are": ("есть / являются", "vannak"),
    "with": ("с", "-val / -vel"),
    "as": ("как", "mint"),
    "i": ("я", "én"),
    "his": ("его", "az ő"),
    "they": ("они", "ők"),
    "be": ("быть", "lenni"),
    "at": ("у / в", "-nál / -nél"),
    "one": ("один", "egy"),
    "have": ("иметь", "van / birtokol"),
    "this": ("этот", "ez"),
    "from": ("из / от", "-ból / -ből / -tól"),
    "or": ("или", "vagy"),
    "had": ("имел / был", "volt / volt neki"),
    "by": ("по / посредством", "által"),
    "but": ("но", "de"),
    "some": ("несколько", "néhány"),
    "what": ("что", "mi"),
    "there": ("там / есть", "ott / van"),
    "we": ("мы", "mi"),
    "out": ("снаружи / наружу", "kint / ki"),
    "other": ("другой", "más"),
    "were": ("были", "voltak"),
    "all": ("все", "mind / minden"),
    "your": ("твой / ваш", "tiéd / öné"),
    "when": ("когда", "mikor"),
    "up": ("вверх", "fel"),
    "use": ("использовать", "használ"),
    "how": ("как", "hogyan"),
    "said": ("сказал", "mondta"),
    "an": ("один / артикль", "egy"),
    "each": ("каждый", "minden / egyenként"),
    "which": ("который / какой", "melyik / amely"),
    "do": ("делать", "csinál"),
    "their": ("их", "az ő"),
    "if": ("если", "ha"),
    "will": ("будет / воля", "fog / akarat"),
    "way": ("путь / способ", "út / mód"),
    "about": ("о / около", "ról / körül"),
    "then": ("тогда", "akkor"),
    "them": ("их", "őket"),
    "would": ("бы", "-na / -ne"),
    "so": ("так / поэтому", "így / ezért"),
    "her": ("её", "őt / az ő"),
    "him": ("его", "őt"),
    "has": ("имеет", "van neki"),
    "could": ("мог бы", "tudna"),
    "did": ("сделал", "tette"),
    "my": ("мой", "az én"),
    "may": ("может", "lehet"),
    "been": ("был", "volt"),
    "any": ("любой / какой-нибудь", "bármely"),
    "made": ("сделал / сделанный", "készített"),
    "came": ("пришёл", "jött"),
    "show": ("показывать", "mutat"),
    "every": ("каждый", "minden"),
    "our": ("наш", "miénk"),
    "round": ("круглый / вокруг", "kerek / körül"),
    "does": ("делает", "tesz / csinál"),
    "sentence": ("предложение", "mondat"),
    "set": ("набор / ставить", "készlet / tesz"),
    "well": ("хорошо", "jól"),
    "must": ("должен", "kell"),
    "men": ("мужчины", "férfiak"),
    "went": ("пошёл", "ment"),
    "us": ("нас", "minket"),
    "self": ("сам", "önmaga"),
    "own": ("собственный", "saját"),
    "page": ("страница", "oldal"),
    "should": ("следует", "kellene"),
    "found": ("нашёл", "talált"),
    "grow": ("расти", "nő"),
    "still": ("всё ещё", "még"),
    "thought": ("мысль / думал", "gondolat / gondolt"),
    "never": ("никогда", "soha"),
    "last": ("последний", "utolsó"),
    "between": ("между", "között"),
    "since": ("с тех пор / с", "óta / mivel"),
    "might": ("мог бы", "talán / lehet"),
    "saw": ("видел", "látta"),
    "while": ("пока / в то время", "amíg / miközben"),
    "press": ("нажимать", "nyom"),
    "seem": ("казаться", "tűnik"),
    "begin": ("начинать", "kezd"),
    "got": ("получил", "kapott"),
    "ease": ("лёгкость", "könnyűség"),
    "often": ("часто", "gyakran"),
    "always": ("всегда", "mindig"),
    "those": ("те", "azok"),
    "both": ("оба", "mindkettő"),
    "mark": ("отметка", "jel"),
    "until": ("до тех пор", "amíg"),
    "mile": ("миля", "mérföld"),
    "feet": ("ступни / футы", "lábak"),
    "care": ("забота", "gondoskodás"),
    "carry": ("нести", "visz"),
    "began": ("начал", "kezdett"),
    "idea": ("идея", "ötlet"),
    "once": ("однажды / один раз", "egyszer"),
    "base": ("основа", "alap"),
    "hear": ("слышать", "hall"),
    "sure": ("уверенный", "biztos"),
    "main": ("главный", "fő"),
}

TOP_ENGLISH_300 = """
the of to and a in is it you that he was for on are with as I his they be at one have this from or had by hot but some what there we can out other were all your when up use word how said an each she which do their time if will way about many then them would write like so these her long make thing see him two has look more day could go come did my sound no most number who over know water than call first people may down side been now find any new work part take get place made live where after back little only round man year came show every good me give our under name very through just form much great think say help low line before turn cause same mean differ move right boy old too does tell sentence set three want air well also play small end put home read hand port large spell add even land here must big high such follow act why ask men change went light kind off need house picture try us again animal point mother world near build self earth father head stand own page should country found answer school grow study still learn plant cover food sun four thought let keep eye never last door between city tree cross since hard start might story saw far sea draw left late run don't while press close night real life few stop open seem together next white children begin got walk example ease paper often always music those both mark book letter until mile river car feet care second group carry rain eat room friend began idea fish mountain north once base hear horse cut sure watch color face wood main
enough
"""

TOP_HUNGARIAN_300 = """
a hogy nem egy meg csak vagy van volt már kell még és mint azt akkor sem lehet mert minden olyan szerint pedig ezt így után úgy nagy fel majd két nem nagyon aki most több lesz itt ha magyar ami első között hanem jó nincs más mi alatt sok ember ott maga mégis akinek ahhoz vagyok mindig miatt mellett kis lenne sokat mit igen vannak előtt egész jól nélkül ebben lett azért eztől mind néhány ma milyen mely mind valami viszont áll tehát inkább legyen három tudom amelyek éves ezek adott nagyobb például magyar szükséges együtt azok akár tovább ennek nekem megfelelő őket szó elég hozzá erre neki ezzel következő esetén mivel ezen belül éppen közül fontos jobb benne magát ezt esetben talán különböző program voltak fog teljesen maga rendszer nap egyes található vele ebben kellett második túl minden egyre csak arról valaki ennek óta emberek egyéb ahogy semmi tudja azzal ugyanis került ellen mondta miért aztán című kicsit módon vissza bár világ abban legnagyobb legalább mindenki azt jelent újra persze részt tud kívül eddig most össze keresztül biztos utolsó isten idő azon itt kerül szinte egyetlen dolog szép mikor mégis érdekében felé mai szemben sokkal jog hogyan összes gazdasági ide nemzetközi szerintem míg további képes szakmai legjobb így amelyet általában újabb évi szóló tovább kellene hosszú kapcsolatban helyi jobban politikai kapcsolatos régi ezek cég szabad egyszer része azokat emberi teszi készült számos közös sikerült rossz közben hasonló lévő hazai törvény történt segítségével száma élet kapott igaz mindent esetleg még külön oldal bizonyos végén budapest történő elő amerikai jelentős angol évben vonatkozó álló elsősorban ország jelenleg többi jelenleg alá európai vagyunk négy szükség természetesen éve évek hát film melyek azaz megy magas elmúlt lehetséges
pár sőt amelynek szintén általános csupán igazán német esetében mintha később igazi először nemcsak ahhoz
"""


KEYWORD_TRANSLATIONS: list[tuple[str, tuple[str, str]]] = [
    ("particle", ("частица", "partikula")),
    ("measure word", ("счётное слово", "számlálószó")),
    ("not", ("не / нет", "nem")),
    ("person", ("человек", "ember")),
    ("people", ("люди", "emberek")),
    ("friend", ("друг", "barát")),
    ("family", ("семья", "család")),
    ("school", ("школа", "iskola")),
    ("student", ("ученик / студент", "diák")),
    ("teacher", ("учитель", "tanár")),
    ("time", ("время", "idő")),
    ("day", ("день", "nap")),
    ("year", ("год", "év")),
    ("month", ("месяц", "hónap")),
    ("money", ("деньги", "pénz")),
    ("food", ("еда", "étel")),
    ("restaurant", ("ресторан", "étterem")),
    ("water", ("вода", "víz")),
    ("tea", ("чай", "tea")),
    ("coffee", ("кофе", "kávé")),
    ("shop", ("магазин", "bolt")),
    ("store", ("магазин", "üzlet")),
    ("work", ("работа", "munka")),
    ("go", ("идти / ехать", "megy")),
    ("come", ("приходить", "jön")),
    ("see", ("видеть", "lát")),
    ("look", ("смотреть", "néz")),
    ("say", ("говорить", "mond")),
    ("speak", ("говорить", "beszél")),
    ("write", ("писать", "ír")),
    ("read", ("читать", "olvas")),
    ("study", ("учиться", "tanul")),
    ("learn", ("учиться", "tanul")),
    ("buy", ("покупать", "vesz")),
    ("sell", ("продавать", "elad")),
    ("eat", ("есть", "eszik")),
    ("drink", ("пить", "iszik")),
    ("sleep", ("спать", "alszik")),
    ("big", ("большой", "nagy")),
    ("small", ("маленький", "kicsi")),
    ("good", ("хороший", "jó")),
    ("bad", ("плохой", "rossz")),
    ("hot", ("горячий", "forró")),
    ("cold", ("холодный", "hideg")),
    ("many", ("много", "sok")),
    ("much", ("много", "sok")),
    ("few", ("мало", "kevés")),
    ("number", ("номер / число", "szám")),
    ("question", ("вопрос", "kérdés")),
    ("can", ("мочь", "tud")),
    ("want", ("хотеть", "akar")),
    ("need", ("нужно", "kell")),
    ("think", ("думать", "gondol")),
    ("know", ("знать", "tud / ismer")),
    ("love", ("любить", "szeret")),
]


def _translate_fallback(english: str, language: str) -> str:
    cleaned = _clean_english(english)
    normalized = cleaned.lower().strip(" .")
    common = COMMON_ENGLISH_TRANSLATIONS.get(normalized)
    if common:
        return common[0 if language == "ru" else 1]
    exact = EXACT_TRANSLATIONS.get(normalized)
    if exact is None:
        exact = next((value for key, value in EXACT_TRANSLATIONS.items() if key.lower() == normalized), None)
    if exact:
        return exact[0 if language == "ru" else 1]
    if any(separator in normalized for separator in (";", ",", " / ")):
        parts = [part.strip() for part in re.split(r";|,| / ", cleaned) if part.strip()]
        translated = [_translate_fallback(part, language) for part in parts[:3]]
        if translated and any(part.lower() != original.lower() for part, original in zip(translated, parts)):
            return " / ".join(translated)
    for keyword, translations in KEYWORD_TRANSLATIONS:
        if keyword in normalized:
            return translations[0 if language == "ru" else 1]
    return cleaned


def _translate_hungarian(hungarian: str, language: str) -> str:
    normalized = hungarian.lower().strip(" .")
    common = COMMON_HUNGARIAN_TRANSLATIONS.get(normalized)
    if common:
        return common[0 if language == "en" else 1]
    for english, (_, hu) in EXACT_TRANSLATIONS.items():
        candidates = [part.strip().lower() for part in re.split(r"/|;", hu)]
        if normalized in candidates or normalized == hu.lower():
            return english if language == "en" else _translate_fallback(english, "ru")
    return hungarian


def enrich_words(raw_words: list[dict]) -> list[dict]:
    enriched: list[dict] = []
    for i, item in enumerate(raw_words):
        word = WordEntry.from_dict(item, i + 1)
        known = LOOKUP.get(word.chinese)
        locks = set(word.lockedFields)
        if known:
            if not word.pinyin and "pinyin" not in locks:
                word.pinyin = known.pinyin
            if not word.english and "english" not in locks:
                word.english = known.english
            if not word.target and "target" not in locks:
                word.target = known.target
            if not word.hungarian and "hungarian" not in locks:
                word.hungarian = known.hungarian
        enriched.append(word.to_dict())
    return enriched
